# Generated by Django 3.2 on 2023-09-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_shoppingcart_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='pub_date',
        ),
    ]
